/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.blankedv.javapanel;

import static de.blankedv.javapanel.Defines.*;
import static de.blankedv.javapanel.JavaPanel.frame;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author mblank
 */
public class SettingsUI extends javax.swing.JFrame {

    private String pName="?";
    
    /**
     * Creates new form SettingsUI
     */
    public SettingsUI(String pName) {
        this.pName = pName;
        
        initComponents();

        initValues();  // read initial values from prefs
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comboScale = new javax.swing.JComboBox<>();
        lblScale = new javax.swing.JLabel();
        cbShowAddresses = new javax.swing.JCheckBox();
        cbStartOfDay = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lblConfigFileName = new javax.swing.JLabel();
        cbSimulation = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        cbRoutesEnabled = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings");

        btnCancel.setText("Zurück");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Speichern");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        comboScale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auto", "1", "1.5", "2", "3", "4", "maximize" }));
        comboScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboScaleActionPerformed(evt);
            }
        });

        lblScale.setText("Scale");

        cbShowAddresses.setText("Show Addresses");

        cbStartOfDay.setText("Send Start-of-Day");
        cbStartOfDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStartOfDayActionPerformed(evt);
            }
        });

        jLabel1.setText("Config File:");

        lblConfigFileName.setText("?");

        cbSimulation.setText("Simulation only");

        jButton1.setText("Open New Config File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbRoutesEnabled.setText("enable Routes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(lblConfigFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbStartOfDay)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSimulation))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblScale)
                                .addGap(33, 33, 33)
                                .addComponent(comboScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbRoutesEnabled)
                                .addComponent(cbShowAddresses)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblConfigFileName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cbRoutesEnabled))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbShowAddresses)
                    .addComponent(cbStartOfDay))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSimulation)
                    .addComponent(lblScale)
                    .addComponent(comboScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       // settingsWindow = null;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        prefs.putBoolean("showAddresses", cbShowAddresses.isSelected());
        prefs.putBoolean("startofday", cbStartOfDay.isSelected());
        prefs.putBoolean("simulation", cbSimulation.isSelected());
        prefs.putBoolean("routesEnabled", cbRoutesEnabled.isSelected());
        prefs.put("scale", comboScale.getSelectedItem().toString());
        prefs.put("configfilename", lblConfigFileName.getText());
        if (DEBUG) {
            System.out.println("saving Settings");
            System.out.println("saving StartOfDay="+cbStartOfDay.isSelected());
            System.out.println("saving Simulation="+cbSimulation.isSelected());
            System.out.println("saving routesEnabled="+cbRoutesEnabled.isSelected());
            System.out.println("showAddresses="+cbShowAddresses.isSelected());
            System.out.println("configfilename="+lblConfigFileName.getText());
            System.out.println("scale="+comboScale.getSelectedItem().toString());
        }
        drawAddresses = prefs.getBoolean("showAddresses", false);
        drawAddresses2 = prefs.getBoolean("showAddresses", false);
        routesEnabled = prefs.getBoolean("routesEnabled", false);
        JOptionPane.showMessageDialog(this,"Program needs Restart if settings have changed.");
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboScaleActionPerformed
        prefs.put("scale", comboScale.getSelectedItem().toString());
    }//GEN-LAST:event_comboScaleActionPerformed

    private void cbStartOfDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStartOfDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStartOfDayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Panel XML Files","xml"));
        int returnVal = fc.showOpenDialog(frame);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            lblConfigFileName.setText(file.getAbsolutePath());

        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void initValues() {
        if (DEBUG) System.out.println("init values of settings");
        
        // read scaling
        String s = prefs.get("scale", "auto");
        comboScale.setSelectedItem(s);
        cbSimulation.setSelected(prefs.getBoolean("simulation", false));
        cbStartOfDay.setSelected(prefs.getBoolean("startOfDay", false));
        cbShowAddresses.setSelected(prefs.getBoolean("showAddresses", false));
        cbRoutesEnabled.setSelected(prefs.getBoolean("routesEnabled", false));
        lblConfigFileName.setText(prefs.get("configfilename",LOCAL_DIRECTORY + "/" + CONFIG_FILENAME));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbRoutesEnabled;
    private javax.swing.JCheckBox cbShowAddresses;
    private javax.swing.JCheckBox cbSimulation;
    private javax.swing.JCheckBox cbStartOfDay;
    private javax.swing.JComboBox<String> comboScale;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfigFileName;
    private javax.swing.JLabel lblScale;
    // End of variables declaration//GEN-END:variables

    
}
